### ISSUE TITLE
Does command:extension.gherkin-pdf.pdf support the export for the whole features folder?

### ISSUE THREAD

**Issue by anniepapa** [TestEssence/vscode-gherkin-pdf#12]
Dear vscode-gherkin-pdf team.
Very nice extension and I'm using it for documenting scenarios and test cases.
However haven't figured out how to export the whole features/ folder in one go in the automated fashion.
I'm considering to use it as part of automation of documentation if you have command line interface or export on folder possible.
Thank you very much!

**Comment by fguidobaldi** [comment]
Hi! Really looking forward for this extension to be available as a CLI tool!

In the meantime, is there any workaround to achieve this? i.e downloading the repo and executing some function as part of an npm script maybe.

Thanks!

**Comment by anatolysakhno** [comment]
@fguidobaldi @anniepapa I have published an npm package you can use for bulk conversion: [feature-to-md](https://www.npmjs.com/package/feature-to-md).
The package is not tested well yet, please submit issues you found  [here](https://github.com/TestEssence/feature-to-md/issues)
You can utilize [md-to-pdf](https://www.npmjs.com/package/md-to-pdf) to convert the resulting markdown into pdfs
